version: '3.8'

services:
  app:
    build:
      context: .
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle 
volumes:
  bundle:
